name: Build Linux Executable

on:
  push:
    branches:
      - main  # Runs the workflow every time code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Runs the workflow for pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller 
          pip install dash dash-html-components dash-core-components dash-bootstrap-components 
          pip install dash-spinner dash_table

      - name: Create Executable with PyInstaller
        run: |
          pyinstaller kinetic_analysis/app_dash_ubuntu_gh.spec

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: KineticAnalysisUbuntu
          path: dist/
