name: Build macOS Executable

on:
  push:
    branches:
      - main  # Runs the workflow every time code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Runs the workflow for pull requests to the 'main' branch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Choose the Python version you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller dash

      - name: Create Executable with PyInstaller
        run: |
          pyinstaller --onefile app_dash.py

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: macos-dash-app
          path: dist/KineticAnalysisMac
